# Generated by Django 3.1.4 on 2020-12-14 11:49

import deepfake.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.EmailField(default='Enter', max_length=128, verbose_name='사용자 이메일')),
                ('file', models.FileField(upload_to=deepfake.models.user_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv'])], verbose_name='동영상 파일')),
            ],
        ),
    ]
